CARETE TABLE ANIME(

PEOPLEID VARCHAR(20),   
PEOPLEPASSWORD VARCHAR(20),  
PEOPLENAME VARCHAR(20),      
PRIMARY KEY(PEOPLEID)
);

INSERT INTO ANIME(PEOPLEID, PEOPLEPASSWORD, PEOPLENAME) VALUES(?, ?, ?);

CARETE TABLE ANIMELIST(

ANIMEID INT,
ANIMETITLE VARCHAR(50),   
PEOPLEID VARCHAR(20),  
ANIMEDATE DATETIME,        
ANIMECONTENT VARCHAR(2048),   
ANIMETYPE VARCHAR(30),
ANIMECANDY VARCHAR(1), 
ANIMEAVAILABLE INT,
PRIMARY KEY(ANIMEID)
);

INSERT INTO ANIMELIST(animeID, animeTitle, peopleID, animeDate, animeContent, animeType, animeCandy, animeAvailable) VALUES(?,?,?,?,?,?,?,?);
SELECT * FROM ANIMELIST WHERE animeID = ?;
UPDATE ANIMELIST SET animeTitle = ?, animeContent2 = ?, animeType = ?, animeCandy = ? WHERE ANIMEID = ?;
DELETE FROM ANIMELIST WHERE animeID=?;
